import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, team, shreyash }) {
  return (
    <html
      lang="en">
      <body className="w-screen h-screen flex">
        <div className="w-[30%] bg-amber-900"> {children}   </div>
        <div className="w-[30%]" > {team} </div>
        <div className="w-[40%] bg-amber-700" > {shreyash} </div>
      </body>
    </html>
  );
}